version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      # test: ["CMD", "netstat", "-ano", "|findstr", "/i", "27017"]
      # test: ["CMD", "curl", "-f","www.google.com"]
      test: ["CMD-SHELL", "curl -f localhost:27017 || exit 0"]
      interval: 5s
      timeout: 5s
      retries: 3
      # start_period: 5s
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      mongodb:
        condition: service_healthy

  my-app:
    image: registrygaming.jfrog.io/virtual-gaming/my-app:1.0
    ports:
      - 3000:3000
    depends_on:
      mongodb:
        condition: service_healthy
volumes:
  mongo-data:
    driver: local